[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
major_version_zero = true
update_changelog_on_bump = true
version = "0.0.0"
version_files = ["Cargo.toml", "Cargo.lock"]
version_provider = "cargo"
